name: Cache Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: prime-cache-a3a8fa6   # Step name as requested
        id: prime_cache              # ID used to reference outputs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-a3a8fa6        # Cache key as requested

      - name: Echo cache hit/miss
        run: |
          if [ "${{ steps.prime_cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
